apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - resources/metrics-server.yaml
patchesStrategicMerge:
  - critical-addon-tolleration.yaml
  - pod-nanny.yaml
