apiVersion: apps/v1
kind: Deployment
metadata:
  name: alb-ingress-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: alb-ingress-controller
        args:
          - --cluster-name=${cluster_name}
