name: trivy-pr-commenter
on:
  pull_request:
jobs:
  trivy:
    name: trivy PR commenter
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: trivy
        uses: reviewdog/action-trivy@v1.13.10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trivy_command: config
          trivy_target: .
          level: info
          reporter: github-pr-review
          filter_mode: nofilter
